/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMy_coursesRouteImport } from './routes/_app/my_courses'
import { Route as AppGradesRouteImport } from './routes/_app/grades'
import { Route as AppCourseCourseIdIndexRouteImport } from './routes/_app/course/$courseId/index'
import { Route as AppCourseCourseIdRedactIndexRouteImport } from './routes/_app/course/$courseId/redact/index'
import { Route as AppCourseCourseIdPanelIndexRouteImport } from './routes/_app/course/$courseId/panel/index'
import { Route as AppCourseCourseIdVideoVideoIdRouteImport } from './routes/_app/course/$courseId/video/$videoId'
import { Route as AppCourseCourseIdResourceResourceIdRouteImport } from './routes/_app/course/$courseId/resource/$resourceId'
import { Route as AppCourseCourseIdAssignmentAssignmentIdRouteImport } from './routes/_app/course/$courseId/assignment/$assignmentId'
import { Route as AppCourseCourseIdTestTestIdIndexRouteImport } from './routes/_app/course/$courseId/test/$testId/index'
import { Route as AppCourseCourseIdTestTestIdAttemptIndexRouteImport } from './routes/_app/course/$courseId/test/$testId/attempt/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMy_coursesRoute = AppMy_coursesRouteImport.update({
  id: '/my_courses',
  path: '/my_courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCourseCourseIdIndexRoute = AppCourseCourseIdIndexRouteImport.update({
  id: '/course/$courseId/',
  path: '/course/$courseId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCourseCourseIdRedactIndexRoute =
  AppCourseCourseIdRedactIndexRouteImport.update({
    id: '/course/$courseId/redact/',
    path: '/course/$courseId/redact/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCourseCourseIdPanelIndexRoute =
  AppCourseCourseIdPanelIndexRouteImport.update({
    id: '/course/$courseId/panel/',
    path: '/course/$courseId/panel/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCourseCourseIdVideoVideoIdRoute =
  AppCourseCourseIdVideoVideoIdRouteImport.update({
    id: '/course/$courseId/video/$videoId',
    path: '/course/$courseId/video/$videoId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCourseCourseIdResourceResourceIdRoute =
  AppCourseCourseIdResourceResourceIdRouteImport.update({
    id: '/course/$courseId/resource/$resourceId',
    path: '/course/$courseId/resource/$resourceId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCourseCourseIdAssignmentAssignmentIdRoute =
  AppCourseCourseIdAssignmentAssignmentIdRouteImport.update({
    id: '/course/$courseId/assignment/$assignmentId',
    path: '/course/$courseId/assignment/$assignmentId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCourseCourseIdTestTestIdIndexRoute =
  AppCourseCourseIdTestTestIdIndexRouteImport.update({
    id: '/course/$courseId/test/$testId/',
    path: '/course/$courseId/test/$testId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppCourseCourseIdTestTestIdAttemptIndexRoute =
  AppCourseCourseIdTestTestIdAttemptIndexRouteImport.update({
    id: '/course/$courseId/test/$testId/attempt/',
    path: '/course/$courseId/test/$testId/attempt/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteRouteWithChildren
  '/grades': typeof AppGradesRoute
  '/my_courses': typeof AppMy_coursesRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/course/$courseId/': typeof AppCourseCourseIdIndexRoute
  '/course/$courseId/assignment/$assignmentId': typeof AppCourseCourseIdAssignmentAssignmentIdRoute
  '/course/$courseId/resource/$resourceId': typeof AppCourseCourseIdResourceResourceIdRoute
  '/course/$courseId/video/$videoId': typeof AppCourseCourseIdVideoVideoIdRoute
  '/course/$courseId/panel/': typeof AppCourseCourseIdPanelIndexRoute
  '/course/$courseId/redact/': typeof AppCourseCourseIdRedactIndexRoute
  '/course/$courseId/test/$testId/': typeof AppCourseCourseIdTestTestIdIndexRoute
  '/course/$courseId/test/$testId/attempt/': typeof AppCourseCourseIdTestTestIdAttemptIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteRouteWithChildren
  '/grades': typeof AppGradesRoute
  '/my_courses': typeof AppMy_coursesRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/course/$courseId': typeof AppCourseCourseIdIndexRoute
  '/course/$courseId/assignment/$assignmentId': typeof AppCourseCourseIdAssignmentAssignmentIdRoute
  '/course/$courseId/resource/$resourceId': typeof AppCourseCourseIdResourceResourceIdRoute
  '/course/$courseId/video/$videoId': typeof AppCourseCourseIdVideoVideoIdRoute
  '/course/$courseId/panel': typeof AppCourseCourseIdPanelIndexRoute
  '/course/$courseId/redact': typeof AppCourseCourseIdRedactIndexRoute
  '/course/$courseId/test/$testId': typeof AppCourseCourseIdTestTestIdIndexRoute
  '/course/$courseId/test/$testId/attempt': typeof AppCourseCourseIdTestTestIdAttemptIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/grades': typeof AppGradesRoute
  '/_app/my_courses': typeof AppMy_coursesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/course/$courseId/': typeof AppCourseCourseIdIndexRoute
  '/_app/course/$courseId/assignment/$assignmentId': typeof AppCourseCourseIdAssignmentAssignmentIdRoute
  '/_app/course/$courseId/resource/$resourceId': typeof AppCourseCourseIdResourceResourceIdRoute
  '/_app/course/$courseId/video/$videoId': typeof AppCourseCourseIdVideoVideoIdRoute
  '/_app/course/$courseId/panel/': typeof AppCourseCourseIdPanelIndexRoute
  '/_app/course/$courseId/redact/': typeof AppCourseCourseIdRedactIndexRoute
  '/_app/course/$courseId/test/$testId/': typeof AppCourseCourseIdTestTestIdIndexRoute
  '/_app/course/$courseId/test/$testId/attempt/': typeof AppCourseCourseIdTestTestIdAttemptIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grades'
    | '/my_courses'
    | '/profile'
    | '/login'
    | '/register'
    | '/course/$courseId/'
    | '/course/$courseId/assignment/$assignmentId'
    | '/course/$courseId/resource/$resourceId'
    | '/course/$courseId/video/$videoId'
    | '/course/$courseId/panel/'
    | '/course/$courseId/redact/'
    | '/course/$courseId/test/$testId/'
    | '/course/$courseId/test/$testId/attempt/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grades'
    | '/my_courses'
    | '/profile'
    | '/login'
    | '/register'
    | '/course/$courseId'
    | '/course/$courseId/assignment/$assignmentId'
    | '/course/$courseId/resource/$resourceId'
    | '/course/$courseId/video/$videoId'
    | '/course/$courseId/panel'
    | '/course/$courseId/redact'
    | '/course/$courseId/test/$testId'
    | '/course/$courseId/test/$testId/attempt'
  id:
    | '__root__'
    | '/_app'
    | '/_app/grades'
    | '/_app/my_courses'
    | '/_app/profile'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/course/$courseId/'
    | '/_app/course/$courseId/assignment/$assignmentId'
    | '/_app/course/$courseId/resource/$resourceId'
    | '/_app/course/$courseId/video/$videoId'
    | '/_app/course/$courseId/panel/'
    | '/_app/course/$courseId/redact/'
    | '/_app/course/$courseId/test/$testId/'
    | '/_app/course/$courseId/test/$testId/attempt/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my_courses': {
      id: '/_app/my_courses'
      path: '/my_courses'
      fullPath: '/my_courses'
      preLoaderRoute: typeof AppMy_coursesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/grades': {
      id: '/_app/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/$courseId/': {
      id: '/_app/course/$courseId/'
      path: '/course/$courseId'
      fullPath: '/course/$courseId/'
      preLoaderRoute: typeof AppCourseCourseIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/$courseId/redact/': {
      id: '/_app/course/$courseId/redact/'
      path: '/course/$courseId/redact'
      fullPath: '/course/$courseId/redact/'
      preLoaderRoute: typeof AppCourseCourseIdRedactIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/$courseId/panel/': {
      id: '/_app/course/$courseId/panel/'
      path: '/course/$courseId/panel'
      fullPath: '/course/$courseId/panel/'
      preLoaderRoute: typeof AppCourseCourseIdPanelIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/$courseId/video/$videoId': {
      id: '/_app/course/$courseId/video/$videoId'
      path: '/course/$courseId/video/$videoId'
      fullPath: '/course/$courseId/video/$videoId'
      preLoaderRoute: typeof AppCourseCourseIdVideoVideoIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/$courseId/resource/$resourceId': {
      id: '/_app/course/$courseId/resource/$resourceId'
      path: '/course/$courseId/resource/$resourceId'
      fullPath: '/course/$courseId/resource/$resourceId'
      preLoaderRoute: typeof AppCourseCourseIdResourceResourceIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/$courseId/assignment/$assignmentId': {
      id: '/_app/course/$courseId/assignment/$assignmentId'
      path: '/course/$courseId/assignment/$assignmentId'
      fullPath: '/course/$courseId/assignment/$assignmentId'
      preLoaderRoute: typeof AppCourseCourseIdAssignmentAssignmentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/$courseId/test/$testId/': {
      id: '/_app/course/$courseId/test/$testId/'
      path: '/course/$courseId/test/$testId'
      fullPath: '/course/$courseId/test/$testId/'
      preLoaderRoute: typeof AppCourseCourseIdTestTestIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/$courseId/test/$testId/attempt/': {
      id: '/_app/course/$courseId/test/$testId/attempt/'
      path: '/course/$courseId/test/$testId/attempt'
      fullPath: '/course/$courseId/test/$testId/attempt/'
      preLoaderRoute: typeof AppCourseCourseIdTestTestIdAttemptIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppGradesRoute: typeof AppGradesRoute
  AppMy_coursesRoute: typeof AppMy_coursesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppCourseCourseIdIndexRoute: typeof AppCourseCourseIdIndexRoute
  AppCourseCourseIdAssignmentAssignmentIdRoute: typeof AppCourseCourseIdAssignmentAssignmentIdRoute
  AppCourseCourseIdResourceResourceIdRoute: typeof AppCourseCourseIdResourceResourceIdRoute
  AppCourseCourseIdVideoVideoIdRoute: typeof AppCourseCourseIdVideoVideoIdRoute
  AppCourseCourseIdPanelIndexRoute: typeof AppCourseCourseIdPanelIndexRoute
  AppCourseCourseIdRedactIndexRoute: typeof AppCourseCourseIdRedactIndexRoute
  AppCourseCourseIdTestTestIdIndexRoute: typeof AppCourseCourseIdTestTestIdIndexRoute
  AppCourseCourseIdTestTestIdAttemptIndexRoute: typeof AppCourseCourseIdTestTestIdAttemptIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGradesRoute: AppGradesRoute,
  AppMy_coursesRoute: AppMy_coursesRoute,
  AppProfileRoute: AppProfileRoute,
  AppCourseCourseIdIndexRoute: AppCourseCourseIdIndexRoute,
  AppCourseCourseIdAssignmentAssignmentIdRoute:
    AppCourseCourseIdAssignmentAssignmentIdRoute,
  AppCourseCourseIdResourceResourceIdRoute:
    AppCourseCourseIdResourceResourceIdRoute,
  AppCourseCourseIdVideoVideoIdRoute: AppCourseCourseIdVideoVideoIdRoute,
  AppCourseCourseIdPanelIndexRoute: AppCourseCourseIdPanelIndexRoute,
  AppCourseCourseIdRedactIndexRoute: AppCourseCourseIdRedactIndexRoute,
  AppCourseCourseIdTestTestIdIndexRoute: AppCourseCourseIdTestTestIdIndexRoute,
  AppCourseCourseIdTestTestIdAttemptIndexRoute:
    AppCourseCourseIdTestTestIdAttemptIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
