/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMy_coursesRouteImport } from './routes/_app/my_courses'
import { Route as AppGradesRouteImport } from './routes/_app/grades'
import { Route as AppCourseCourseIdRouteImport } from './routes/_app/course/$courseId'
import { Route as AppCourseAssignmentAssignmentIdRouteImport } from './routes/_app/course/assignment/$assignmentId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMy_coursesRoute = AppMy_coursesRouteImport.update({
  id: '/my_courses',
  path: '/my_courses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCourseCourseIdRoute = AppCourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCourseAssignmentAssignmentIdRoute =
  AppCourseAssignmentAssignmentIdRouteImport.update({
    id: '/course/assignment/$assignmentId',
    path: '/course/assignment/$assignmentId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRouteRouteWithChildren
  '/grades': typeof AppGradesRoute
  '/my_courses': typeof AppMy_coursesRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/course/$courseId': typeof AppCourseCourseIdRoute
  '/course/assignment/$assignmentId': typeof AppCourseAssignmentAssignmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRouteRouteWithChildren
  '/grades': typeof AppGradesRoute
  '/my_courses': typeof AppMy_coursesRoute
  '/profile': typeof AppProfileRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/course/$courseId': typeof AppCourseCourseIdRoute
  '/course/assignment/$assignmentId': typeof AppCourseAssignmentAssignmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/grades': typeof AppGradesRoute
  '/_app/my_courses': typeof AppMy_coursesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/course/$courseId': typeof AppCourseCourseIdRoute
  '/_app/course/assignment/$assignmentId': typeof AppCourseAssignmentAssignmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grades'
    | '/my_courses'
    | '/profile'
    | '/login'
    | '/register'
    | '/course/$courseId'
    | '/course/assignment/$assignmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grades'
    | '/my_courses'
    | '/profile'
    | '/login'
    | '/register'
    | '/course/$courseId'
    | '/course/assignment/$assignmentId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/grades'
    | '/_app/my_courses'
    | '/_app/profile'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/course/$courseId'
    | '/_app/course/assignment/$assignmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my_courses': {
      id: '/_app/my_courses'
      path: '/my_courses'
      fullPath: '/my_courses'
      preLoaderRoute: typeof AppMy_coursesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/grades': {
      id: '/_app/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/$courseId': {
      id: '/_app/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof AppCourseCourseIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/course/assignment/$assignmentId': {
      id: '/_app/course/assignment/$assignmentId'
      path: '/course/assignment/$assignmentId'
      fullPath: '/course/assignment/$assignmentId'
      preLoaderRoute: typeof AppCourseAssignmentAssignmentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppGradesRoute: typeof AppGradesRoute
  AppMy_coursesRoute: typeof AppMy_coursesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppCourseCourseIdRoute: typeof AppCourseCourseIdRoute
  AppCourseAssignmentAssignmentIdRoute: typeof AppCourseAssignmentAssignmentIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGradesRoute: AppGradesRoute,
  AppMy_coursesRoute: AppMy_coursesRoute,
  AppProfileRoute: AppProfileRoute,
  AppCourseCourseIdRoute: AppCourseCourseIdRoute,
  AppCourseAssignmentAssignmentIdRoute: AppCourseAssignmentAssignmentIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
